set build_components {
    core init hoitaja timer app/empty_cell
}

build $build_components
create_boot_directory

install_config {
    <config>
        <parent-provides>
            <service name="LOG"/>
            <service name="PD"/>
            <service name="CPU"/>
            <service name="ROM"/>
            <service name="RAM"/>
            <service name="IRQ"/>
            <service name="IO_MEM"/>
            <service name="IO_PORT"/>
            <service name="CAP"/>
            <service name="RM"/>
            <service name="SIGNAL"/>
            <service name="TRACE"/>
        </parent-provides>
        <default-route>
            <any-service><parent/><any-child/></any-service>
        </default-route>
        <default caps="2000"/>
        <start name="timer">
            <resource name="RAM" quantum="3M"/>
            <provides><service name="Timer"/></provides>
            <route>
                <any-service><parent/><any-child/></any-service>
            </route>
        </start>
        <start name="hoitaja" caps="62000">
            <resource name="RAM" quantum="250G"/>
            <config prio_levels="32" verbose="true">
                <parent-provides>
                    <service name="LOG"/>
                    <service name="PD"/>
                    <service name="CPU"/>
                    <service name="ROM"/>
                    <service name="RAM"/>
                    <service name="IRQ"/>
                    <service name="IO_MEM"/>
                    <service name="IO_PORT"/>
                    <service name="CAP"/>
                    <service name="RM"/>
                    <service name="SIGNAL"/>
                    <service name="TRACE"/>
                </parent-provides>
                <default-route>
                    <any-service><parent/><any-child/></any-service>
                </default-route>
                <default caps="600"/>
                <affinity-space width="64" height="1"/>
                <start name="cell1" priority="-1">
                    <binary name="empty_cell"/>
                    <resource name="RAM" quantum="3M"/>
                </start>
                <start name="cell2" priority="-2">
                    <binary name="empty_cell"/>
                    <resource name="RAM" quantum="3M"/>
                </start>
            </config>
        </start>
    </config>   
}

build_boot_image [build_artifacts]

append qemu_args " -nographic "
run_genode_until forever