set build_components {
    core init hoitaja timer lib/ld lib/vfs lib/libm lib/libc lib/stdcxx bench/larson
}

build $build_components
create_boot_directory

install_config {
    <config prio_levels="32" verbose="true">
        <parent-provides>
            <service name="LOG"/>
            <service name="PD"/>
            <service name="CPU"/>
            <service name="ROM"/>
            <service name="RAM"/>
            <service name="IRQ"/>
            <service name="IO_MEM"/>
            <service name="IO_PORT"/>
            <service name="CAP"/>
            <service name="RM"/>
            <service name="SIGNAL"/>
            <service name="TRACE"/>
        </parent-provides>
        <default-route>
            <any-service><parent/><any-child/></any-service>
        </default-route>
        <default caps="2000"/>
        <affinity-space width="64" height="1"/>
        <start name="timer">
            <resource name="RAM" quantum="3M"/>
            <provides><service name="Timer"/></provides>
            <route>
                <any-service><parent/><any-child/></any-service>
            </route>
        </start>
        <start name="cell1" priority="-1" caps="160000">
            <binary name="larson"/>
            <resource name="RAM" quantum="220G"/>
            <config>
                <vfs> <dir name="dev"> 
                    <log/> 
                    <inline name="rtc">2022-07-20 14:30</inline> 
                    </dir>
                </vfs> 
                <libc stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc"/>
            </config>
        </start>
                <!--
                <start name="cell2" priority="-2">
                    <binary name="empty_cell"/>
                    <resource name="RAM" quantum="3M"/>
                </start>
                -->
    </config>   
}

build_boot_image [build_artifacts]

append qemu_args " -nographic "
run_genode_until forever