set build_components {
    core init hoitaja timer lib/ld lib/libm lib/libc lib/stdcxx lib/vfs app/launcher_test app/allocating_cell
}

build $build_components
create_boot_directory

install_config {
<config prio_levels="32" verbose="true">
    <parent-provides>
        <service name="LOG"/>
        <service name="PD"/>
        <service name="CPU"/>
        <service name="ROM"/>
        <service name="RAM"/>
        <service name="IRQ"/>
        <service name="IO_MEM"/>
        <service name="IO_PORT"/>
        <service name="CAP"/>
        <service name="RM"/>
        <service name="SIGNAL"/>
        <service name="TRACE"/>
    </parent-provides>
    <default-route>
        <any-service><parent/><any-child/></any-service>
    </default-route>
    <default caps="2000"/>
    <affinity-space width="64" height="1"/>
    <start name="timer">
        <resource name="RAM" quantum="3M"/>
        <provides><service name="Timer"/></provides>
        <route>
            <any-service><parent/><any-child/></any-service>
        </route>
    </start>
    <start name="cell1" priority="-1">
        <binary name="launcher"/>
        <resource name="RAM" quantum="8M"/>
        <config>
            <vfs> <dir name="dev"> 
                <log/> 
                <inline name="rtc">2022-07-20 14:30</inline> 
                </dir>
            </vfs> 
            <libc stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc"/>
        </config>
        <route>
            <service name="Launcher"><local/></service>
            <any-service><parent/><any-child/></any-service>
        </route>
    </start>
            <!--
            <start name="cell2" priority="-2">
                <binary name="empty_cell"/>
                <resource name="RAM" quantum="3M"/>
            </start>
            -->
</config>   
}

build_boot_image [build_artifacts]

append qemu_args " -nographic "

set succeeded 0
set failed 0

for {set i 0} { $i < 3000 } { incr i } {
    if { ! [catch {run_genode_until ".*Changing cell .* affinity to .*0,0,32.*" 120} result ] } {
        incr succeeded
        puts "\n $succeeded of 3000 succeeded"
        kill_spawned $qemu_spawn_id
    } else {
        incr failed
        kill_spawned $qemu_spawn_id
    }
}

puts "\n $succeeded of $i succeeded. $failed of $i failed."