build 'core init app/thread_test'
create_boot_directory

install_config {
    <config>
        <parent-provides>
            <service name="LOG"/>
            <service name="PD"/>
            <service name="CPU"/>
            <service name="ROM"/>
        </parent-provides>
        <default-route>
            <any-service><parent/></any-service>
        </default-route>
        <default caps="200"/>
        <start name="thread_test">
            <resource name="RAM" quantum="10M"/>
        </start>
    </config>
}
build_boot_image "core ld lib.so init thread_test"
append qemu_args "-nographic -m 64"