build "core init timer app/thread_test"
create_boot_directory

install_config {
    <config>
        <parent-provides>
            <service name="LOG"/>
            <service name="PD"/>
            <service name="CPU"/>
            <service name="ROM"/>
            <service name="RAM"/>
            <service name="IRQ"/>
            <service name="IO_MEM"/>
            <service name="IO_PORT"/>
            <service name="CAP"/>
            <service name="RM"/>
            <service name="SIGNAL"/>
            <service name="TOPO"/>
        </parent-provides>
        <default-route>
            <any-service><parent/><any-child/></any-service>
        </default-route>
        <affinity-space width="16" height="1"/> 
        <default caps="200"/>
        <start name="timer">
            <resource name="RAM" quantum="1M"/>
            <provides><service name="Timer"/></provides>
            <route>
                <any-service><parent/><any-child/></any-service>
            </route>
        </start>
        <start name="thread_test">
            <resource name="RAM" quantum="10M"/>
            <affinity xpos="0" ypos="0" width="8" height="1"/>
            <route>
                <service name="Timer"> <child name="timer"/> </service>
                <any-service><parent/><any-child/></any-service>
            </route>
        </start>
    </config>
}
set boot_modules { 
    core init timer vfs.lib.so ld.lib.so libm.lib.so libc.lib.so stdcxx.lib.so thread_test
}
build_boot_image $boot_modules
append qemu_args "-nographic"
run_genode_until forever
