# build config
build { core init gpgpu timer producer consumer1 consumer2 }

# platform config
set use_acpica_as_acpi_drv 0
source ${genode_dir}/repos/base/run/platform_drv.inc
proc platform_drv_policy {} {
	global use_acpica_as_acpi_drv
	set policy ""

	append_if $use_acpica_as_acpi_drv policy {
			<policy label="acpi_drv -> ">    <pci class="ALL"/> </policy>}

	append policy {
			<policy label_prefix="gpgpu"> <pci class="ALL"/> </policy>}
	append policy {
			<policy label_prefix="producer"> <pci class="ALL"/> </policy>}
	append policy {
			<policy label_prefix="consumer1"> <pci class="ALL"/> </policy>}
	append policy {
			<policy label_prefix="consumer2"> <pci class="ALL"/> </policy>}

	return $policy
}
append_platform_drv_build_components
build $build_components

# boot dir
create_boot_directory

# other config
append config {
	<config>
		<parent-provides>
			<service name="ROM"/>
            <service name="IRQ"/>
            <service name="IO_MEM"/>
			<service name="PD"/>
			<service name="RM"/>
			<service name="CPU"/>
			<service name="LOG"/>
			<service name="RAM"/>
			<service name="CAP"/>
            <service name="TOPO"/>
		</parent-provides>
		<default-route>
			<any-service> <parent/> <any-child/> </any-service>
		</default-route>
		<default caps="200"/>
		<start name="timer">
			<resource name="RAM" quantum="1M"/>
			<provides><service name="Timer"/></provides>
			<route>
				<any-service><parent/><any-child/></any-service>
			</route>
		</start>
}

append_platform_drv_config

append config {
    <start name="gpgpu" priority="0">
		<provides> <service name="gpgpu"/> </provides>
        <resource name="RAM" quantum="12G"/>
    </start>
	<start name="producer">
		<binary name="producer"/>
		<resource name="RAM" quantum="512M"/>
		<config>
			<vfs> <dir name="dev"> <log/> <inline name="rtc">2022-07-20 14:30</inline> </dir> </vfs>
			<libc stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc"/>
		</config>
	</start>
	<start name="consumer (high)">
		<binary name="consumer1"/>
		<resource name="RAM" quantum="512M"/>
		<config>
			<vfs> <dir name="dev"> <log/> <inline name="rtc">2022-07-20 14:30</inline> </dir> </vfs>
			<libc stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc"/>
		</config>
	</start>
	<start name="consumer (low)">
		<binary name="consumer2"/>
		<resource name="RAM" quantum="512M"/>
		<config >
			<vfs> <dir name="dev"> <log/> <inline name="rtc">2022-07-20 14:30</inline> </dir> </vfs>
			<libc stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc"/>
		</config>
	</start>
</config>}

install_config $config

# boot modules
set boot_modules {
	core ld.lib.so libc.lib.so vfs.lib.so libm.lib.so init gpgpu timer producer consumer1 consumer2
}
append_platform_drv_boot_modules
build_boot_image $boot_modules

# qemu stuff
append qemu_args " -nographic -m 24G"
run_genode_until forever
